title: GW2WP - Guild Wars 2 Waypoint Codes
description: Easily search and copy Guild Wars 2 waypoint codes for easy access within the game.
baseurl: ""
permalink: "/:title"
url: ""

plugins:
  - jekyll-autoprefixer

sass:
  sass_dir: _sass
  style: compressed
